name: Publish Package

on:
  workflow_dispatch:

jobs:
  release-branch:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Require main release branch
        run: test "$GITHUB_REF" = 'refs/heads/main'

  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read

  publish:
    needs: [release-branch, ci]
    uses: askrjs/actions/.github/workflows/publish-package.yml@main
    permissions:
      contents: write
      id-token: write
      packages: read
