name: Publish Package

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read

  publish:
    needs: ci
    uses: askrjs/actions/.github/workflows/publish-package.yml@1ecd3e84c32b3ff9bb85111baabbd31f79c459dd
    permissions:
      contents: write
      id-token: write
      packages: read
